// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT2GLE3Nw6-f_qfZ0ruvJuZJBxbLDOgIU',
    appId: '1:458385955417:android:0b9deaadf3aca36bf9af48',
    messagingSenderId: '458385955417',
    projectId: 'rpmqa-ca460',
    databaseURL: 'https://rpmqa-ca460-default-rtdb.firebaseio.com',
    storageBucket: 'rpmqa-ca460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtDX95hFH2wosJvv_Wqz2UegV4tmJ3AFo',
    appId: '1:458385955417:ios:a1069df3d6f1408ff9af48',
    messagingSenderId: '458385955417',
    projectId: 'rpmqa-ca460',
    databaseURL: 'https://rpmqa-ca460-default-rtdb.firebaseio.com',
    storageBucket: 'rpmqa-ca460.appspot.com',
    iosClientId: '458385955417-i2gi8qbc1piopbmjp4362hdhok2lgi25.apps.googleusercontent.com',
    iosBundleId: 'com.bigtheta.rpmqa',
  );
}
